# .github/workflows/deploy.yml
name: Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var="cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID" -var="r2_access_key_id=$R2_ACCESS_KEY_ID" -var="r2_secret_access_key=$R2_SECRET_ACCESS_KEY"
      if: github.ref == 'refs/heads/main'

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID" -var="r2_access_key_id=$R2_ACCESS_KEY_ID" -var="r2_secret_access_key=$R2_SECRET_ACCESS_KEY"
      if: github.ref == 'refs/heads/main'
